# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_location_ezplatform_content_by_class_api:
    pattern:  /api/private/campaignchain/location-ezplatform/content/class/{id}
    defaults: { _controller: CampaignChainLocationEZPlatformBundle:EZPlatform:apiContentByClass }
    options:
        expose: true