# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    # Parameters for the CampaignChain Location modules in this Symfony bundle
    campaignchain.location.campaignchain.ezplatform.user:
        bundle_name: "campaignchain/location-ezplatform"
        module_identifier: "campaignchain-ezplatform-user"
    campaignchain.location.campaignchain.ezplatform.object:
        bundle_name: "campaignchain/location-ezplatform"
        module_identifier: "campaignchain-ezplatform-object"

services: